### ISSUE TITLE
pepper forgot to handle a parse error 😁 

### ISSUE THREAD

**Issue by MAHDTech** [nerdypepper/statix#74]
Receiving this error, trying to track down source.

with `RUST_BACKTRACE=1`

```bash
[bin/src/config.rs:79] [self.ignore.as_slice(), extra_ignores].concat() = []
thread '<unnamed>' panicked at 'report a bug, pepper forgot to handle a parse error', lib/src/lib.rs:111:18
stack backtrace:
   0: std::panicking::begin_panic
   1: lib::Report::from_parse_err
   2: <core::iter::adapters::chain::Chain<A,B> as core::iter::traits::iterator::Iterator>::next
   3: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
   4: statix::lint::lint_with
   5: rayon::iter::plumbing::Folder::consume_iter
   6: rayon::iter::plumbing::bridge_producer_consumer::helper
   7: std::panicking::try
   8: rayon_core::registry::in_worker
   9: rayon::iter::plumbing::bridge_producer_consumer::helper
  10: rayon_core::job::StackJob<L,F,R>::run_inline
  11: rayon_core::registry::in_worker
  12: rayon::iter::plumbing::bridge_producer_consumer::helper
  13: std::panicking::try
  14: rayon_core::registry::in_worker
  15: rayon::iter::plumbing::bridge_producer_consumer::helper
  16: rayon_core::job::StackJob<L,F,R>::run_inline
  17: rayon_core::registry::in_worker
  18: rayon::iter::plumbing::bridge_producer_consumer::helper
  19: std::panicking::try
  20: rayon_core::registry::in_worker
  21: rayon::iter::plumbing::bridge_producer_consumer::helper
  22: std::panicking::try
  23: rayon_core::registry::in_worker
  24: rayon::iter::plumbing::bridge_producer_consumer::helper
  25: std::panicking::try
  26: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  27: rayon_core::registry::WorkerThread::wait_until_cold
  28: rayon_core::registry::in_worker
  29: rayon::iter::plumbing::bridge_producer_consumer::helper
  30: std::panicking::try
  31: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  32: rayon_core::registry::WorkerThread::wait_until_cold
  33: rayon_core::registry::ThreadBuilder::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

with `RUST_BACKTRACE=full`

```bash
[bin/src/config.rs:79] [self.ignore.as_slice(), extra_ignores].concat() = []
thread '<unnamed>' panicked at 'report a bug, pepper forgot to handle a parse error', lib/src/lib.rs:111:18
stack backtrace:
   0:     0x557af089c09c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf2ea00d5f3b53d9f
   1:     0x557af08cdc1e - core::fmt::write::ha076a7e65c6b1874
   2:     0x557af08ae1e1 - std::io::Write::write_fmt::h9630bb3b0fe886f5
   3:     0x557af08b60b5 - std::panicking::default_hook::{{closure}}::h64163197f96398c1
   4:     0x557af08b5d12 - std::panicking::default_hook::h92625161492e6b48
   5:     0x557af08b65d1 - std::panicking::rust_panic_with_hook::hfdd7d6bb6788c6c2
   6:     0x557af0819b5b - std::panicking::begin_panic::{{closure}}::h4d059ca817d6c6df
   7:     0x557af0819b24 - std::sys_common::backtrace::__rust_end_short_backtrace::h4ab22004f531b9ff
   8:     0x557af070b4ba - std::panicking::begin_panic::h2eb13ba9e6a4bba5
   9:     0x557af0812c6d - lib::Report::from_parse_err::h8c081eab22132497
  10:     0x557af073096a - <core::iter::adapters::chain::Chain<A,B> as core::iter::traits::iterator::Iterator>::next::hb90f7780cf67fd73
  11:     0x557af0737d47 - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter::hd50ffdb0ac1db02f
  12:     0x557af07244f6 - statix::lint::lint_with::ha5be777365fdfccb
  13:     0x557af073dbeb - rayon::iter::plumbing::Folder::consume_iter::h5b4dbd78d4649f4d
  14:     0x557af073d6a0 - rayon::iter::plumbing::bridge_producer_consumer::helper::hc08540f1e5437935
  15:     0x557af0748fb4 - std::panicking::try::hc2db50ef75b55d50
  16:     0x557af0714958 - rayon_core::registry::in_worker::hb29ff9a608069be3
  17:     0x557af073d8cf - rayon::iter::plumbing::bridge_producer_consumer::helper::hc08540f1e5437935
  18:     0x557af071e89d - rayon_core::job::StackJob<L,F,R>::run_inline::h587ad141ff928dc2
  19:     0x557af07149e8 - rayon_core::registry::in_worker::hb29ff9a608069be3
  20:     0x557af073d8cf - rayon::iter::plumbing::bridge_producer_consumer::helper::hc08540f1e5437935
  21:     0x557af071e89d - rayon_core::job::StackJob<L,F,R>::run_inline::h587ad141ff928dc2
  22:     0x557af07149e8 - rayon_core::registry::in_worker::hb29ff9a608069be3
  23:     0x557af073d8cf - rayon::iter::plumbing::bridge_producer_consumer::helper::hc08540f1e5437935
24:     0x557af0748fb4 - std::panicking::try::hc2db50ef75b55d50
  25:     0x557af0714958 - rayon_core::registry::in_worker::hb29ff9a608069be3
  26:     0x557af073d8cf - rayon::iter::plumbing::bridge_producer_consumer::helper::hc08540f1e5437935
  27:     0x557af0748fb4 - std::panicking::try::hc2db50ef75b55d50
  28:     0x557af0714958 - rayon_core::registry::in_worker::hb29ff9a608069be3
  29:     0x557af073d8cf - rayon::iter::plumbing::bridge_producer_consumer::helper::hc08540f1e5437935
  30:     0x557af071e89d - rayon_core::job::StackJob<L,F,R>::run_inline::h587ad141ff928dc2
  31:     0x557af07149e8 - rayon_core::registry::in_worker::hb29ff9a608069be3
  32:     0x557af073d8cf - rayon::iter::plumbing::bridge_producer_consumer::helper::hc08540f1e5437935
  33:     0x557af0748f07 - std::panicking::try::h1cf0be7f65475852
  34:     0x557af0721e19 - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::h2b6b1e9c5a8ee7bd
  35:     0x557af0709fe8 - rayon_core::registry::WorkerThread::wait_until_cold::ha2783ad47279d811
  36:     0x557af0714a25 - rayon_core::registry::in_worker::hb29ff9a608069be3
  37:     0x557af073d8cf - rayon::iter::plumbing::bridge_producer_consumer::helper::hc08540f1e5437935
  38:     0x557af0748f07 - std::panicking::try::h1cf0be7f65475852
  39:     0x557af0721e19 - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::h2b6b1e9c5a8ee7bd
  40:     0x557af0709fe8 - rayon_core::registry::WorkerThread::wait_until_cold::ha2783ad47279d811
  41:     0x557af0714a25 - rayon_core::registry::in_worker::hb29ff9a608069be3
  42:     0x557af073d8cf - rayon::iter::plumbing::bridge_producer_consumer::helper::hc08540f1e5437935
  43:     0x557af0748fb4 - std::panicking::try::hc2db50ef75b55d50
  44:     0x557af0714958 - rayon_core::registry::in_worker::hb29ff9a608069be3
  45:     0x557af073d8cf - rayon::iter::plumbing::bridge_producer_consumer::helper::hc08540f1e5437935
  46:     0x557af0748fb4 - std::panicking::try::hc2db50ef75b55d50
  47:     0x557af0714958 - rayon_core::registry::in_worker::hb29ff9a608069be3
  48:     0x557af073d8cf - rayon::iter::plumbing::bridge_producer_consumer::helper::hc08540f1e5437935
  49:     0x557af0748f07 - std::panicking::try::h1cf0be7f65475852
  50:     0x557af0721e19 - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::h2b6b1e9c5a8ee7bd
  51:     0x557af0709fe8 - rayon_core::registry::WorkerThread::wait_until_cold::ha2783ad47279d811
  52:     0x557af0807e70 - rayon_core::registry::ThreadBuilder::run::hfdb510d4c4dc36bd
  53:     0x557af0809aa1 - std::sys_common::backtrace::__rust_begin_short_backtrace::h70e3d732bb19dbe8
  54:     0x557af080b0cd - core::ops::function::FnOnce::call_once{{vtable.shim}}::h02352fcc9a45e6c4
  55:     0x557af08aec53 - std::sys::unix::thread::Thread::new::thread_start::h1f2eb64c3e9233cd
  56:     0x7f0fc413ce86 - start_thread
  57:     0x7f0fc41c3d70 - clone3
  58:                0x0 - <unknown>
```

**Comment by mightyiam** [comment]
https://github.com/molybdenumsoftware/statix/commit/9535d18cfb0c16253a230f2712005ef7cfda5698
